#ddev-generated
hooks:
  # This will be executed whenever DDEV starts
  post-start:
    # This line creates a job, ddev-cron-time, and configures it to run every minute
    # You can just `ls -l time.log` or `tail time.log` to see it happening.
    - exec: echo '* * * * * root date | tee -a /var/www/html/time.log' | sudo tee -a /etc/cron.d/ddev-cron-time
