#ddev-generated
# Remove the line above if you don't want this file to be overwritten when you run
# ddev get drud/ddev-cron
hooks:
  post-start:
    # This adds an every-minute cronjob for your user; it runs "date" and appends that
    # to the "date.log" in your project root.
    # You can just `ls -l date.log` or `tail -f date.log` to see it happening.
    # The crontab can have more than one line for multiple jobs.
    # `ddev exec crontab -l` will show you the current crontab configuration
    - exec: echo "* * * * * date | tee -a /var/www/html/date.log" | crontab
